### PR TITLE
fix(docs): prevent scrolling when user scroll

### LINKED ISSUE #810: Docs: scroll and TOC sync and lags

### PR DESCRIPTION
**Pull request by yggg**
### Please read and mark the following check list before creating a pull request:

 - [x] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/nebular/blob/master/CONTRIBUTING.md) guide.
 - [x] I read and followed the [New Feature Checklist](https://github.com/akveo/nebular/blob/master/DEV_DOCS.md#new-feature-checklist) guide.
 
 #### Short description of what this resolves:
Fixes auto scrolling to page top when trying to scroll to the bottom.
Closes #810.

### CODE REVIEW

File: docs/app/@theme/components/fragment-target/fragment-target.directive.ts [hunk 1]
```diff
@@ -1,73 +1,94 @@
...
           this.selectFragment();
         } else {
           this.deselectFragment();
         }
       });
+
+    this.visibilityService.observe(this.el.nativeElement, OBSERVER_OPTIONS)
+      .pipe(
+        takeWhile(() => this.alive),
+        tap((e: IntersectionObserverEntry) => console.info(`${this.ngdFragment} - ${e.isIntersecting}`)),
```
Comment (nnixaa) [inline docs/app/@theme/components/fragment-target/fragment-target.directive.ts]: let's remove the `console.info`
